# Generated by Django 4.2.6 on 2023-10-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_favorite_product_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
