# Generated by Django 4.2.6 on 2023-10-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('eur', 'EUR'), ('gbp', 'GBP'), ('usd', 'USD'), ('sek', 'SEK')], default='eur', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='test', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
