# Generated by Django 4.2.6 on 2023-10-19 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('meat', 'Meat'), ('fruit', 'Fruit'), ('vegetables', 'Vegetables'), ('wine', 'Wine'), ('beer', 'Beer'), ('honey', 'Honey'), ('nuts', 'Nuts'), ('cheese', 'Cheese'), ('mix', 'Mix of products'), ('other', 'Other')], default='other', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category'),
        ),
    ]
