# Generated by Django 4.2.6 on 2023-10-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('meat', 'Meat'), ('fruit', 'Fruit'), ('vegetables', 'Vegetables'), ('wine', 'Wine'), ('beer', 'Beer'), ('honey', 'Honey'), ('nuts', 'Nuts'), ('cheese', 'Cheese'), ('mix', 'Mix of products'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
