# Generated by Django 4.2.6 on 2023-10-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorited_by',
        ),
    ]
