# Generated by Django 4.2.6 on 2023-10-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
